services:
  ubuntu-01:
    build: 
      context: ./init
      dockerfile: dockerfile.ubuntu
    privileged: true 
    networks:
      - default
    ports:
      - 50000:22
  ubuntu-02:
    build: 
      context: ./init
      dockerfile: dockerfile.ubuntu
    privileged: true 
    networks:
      - default
    ports:
      - 50001:22
  rhel-01:
    build: 
      context: ./init
      dockerfile: dockerfile.rhel
    privileged: true 
    networks:
      - default
    ports:
      - 50002:22
  rhel-02:
    build: 
      context: ./init
      dockerfile: dockerfile.rhel
    privileged: true 
    networks:
      - default
    ports:
      - 50003:22
  alpine-01:
    build: 
      context: ./init
      dockerfile: dockerfile.alpine
    privileged: true 
    networks:
      - default
    ports:
      - 50004:22
  alpine-02:
    build: 
      context: ./init
      dockerfile: dockerfile.alpine
    privileged: true 
    networks:
      - default
    ports:
      - 50005:22
