FROM alpine:latest

# Install SSH client
RUN apk update
RUN apk add openssh openrc --no-cache
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Create a new user
RUN adduser -D -h admin -s /bin/bash admin
RUN echo "admin:password" | chpasswd

# Expose default SSH port
EXPOSE 22

RUN /usr/bin/ssh-keygen -A

ENTRYPOINT /usr/sbin/sshd && tail -f /dev/null