FROM redhat/ubi8:latest

# Install SSH client
RUN dnf update -y
RUN dnf install -y openssh-server initscripts
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Create a new user
RUN useradd -m -s /bin/bash admin
RUN echo "admin:password" | chpasswd

# Expose default SSH port
EXPOSE 22

RUN /usr/bin/ssh-keygen -A

ENTRYPOINT /sbin/sshd && tail -f /dev/null